name: 'SSH to Actions'
author: 'rdp-studio'
description: 'Connect to GitHub Actions VM via SSH for interactive debugging'
inputs:
  mode:
    description: 'choose tmate or ngrok mode'
    required: false
    default: 'tmate'
runs:
  using: "composite"
  steps: 
    - run: $GITHUB_ACTION_PATH/${{ inputs.mode }}2actions.sh
      shell: bash
branding:
  icon: 'terminal'
  color: 'gray-dark'
  
name: Start SSH via tmate
  uses: rdp-studio/ssh2actions@main
  # Send connection info to Telegram (optional)
  # You can find related documents here: https://core.telegram.org/bots
  env:
    TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
    TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
